language: php

matrix:
    include:
        - php: 5.6
        - php: nightly
        - php: hhvm
        - php: hhvm-nightly

before_install:
    - composer self-update
    - sudo locale-gen en_US.UTF-8 && sudo update-locale

install:
    - composer --prefer-dist install

script:
    - vendor/bin/phpunit --exclude-group tty,benchmark,intl-data
